Daily_Rozgaar/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^worker/', include('worker.urls',namespace='worker')),
]

worker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # /worker/
    url(r'^$', views.index, name='index'),

    # /worker/skill/
    url(r'^skill/$', views.skillList, name='skillList'),

    # /worker/skill/skill_name
    url(r'^skill/(?P<skill_name>[A-Za-z][\w|\W]+)/$', views.skillDetail, name='skillDetail'),

    # /worker/city/
    url(r'^city/$', views.cityList, name='cityList'),

    # /worker/city/city_name
    url(r'^city/(?P<city_name>[A-Za-z][\w|\W]+)/$', views.cityDetail, name='cityDetail'),
]

worker/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class skill(models.Model):
	skill_name = models.CharField(max_length=100)
	skill_file = models.FileField()
	def __str__(self):
		return self.skill_name

class city(models.Model):
    city_name = models.CharField(max_length=100)
    city_file = models.FileField()
    def __str__(self):
		return self.city_name

worker/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import skill,city
import rdflib

# Create your views here.
def index(request):
	all_skills = skill.objects.all()
	all_cities = city.objects.all()
	template = loader.get_template('worker/index.html')
	context = {
		'all_skills' : all_skills,
		'all_cities' : all_cities,
	}
	return HttpResponse(template.render(context,request))

def skillList(request):
	all_skills = skill.objects.all()
	template = loader.get_template('worker/skillList.html')
	context = {
		'all_skills' : all_skills,
	}
	return HttpResponse(template.render(context,request))

#changed detail to skill Detail
def skillDetail(request,skill_name):
	sk = get_object_or_404(skill, skill_name=skill_name)
	g=rdflib.Graph()
	g.parse(sk.skill_file)
	res2 = g.query("""
	PREFIX nit: <http://127.0.0.1:3333/>
	SELECT ?fname ?lname ?local ?skill_name ?sub_skill
	WHERE{
	    ?x nit:hasFirstName ?fname.
	    ?x nit:hasLastName ?lname.
	    ?x nit:hasLocality ?local.
	    ?x nit:hasSubSkill ?sub_skill.
	    ?x nit:hasSkill """+"'"+skill_name+"'"+"""
	}
    """)
	
	template = loader.get_template('worker/skillDetail.html')
	context = {
		'skill_name' : skill_name,
		'res2' : res2,
	}
	return HttpResponse(template.render(context,request))

def cityList(request):
	all_cities = city.objects.all()
	template = loader.get_template('worker/cityList.html')
	context = {
		'all_cities' : all_cities,
	}
	return HttpResponse(template.render(context,request))

def cityDetail(request,city_name):
	ct = get_object_or_404(city, city_name=city_name)
	g=rdflib.Graph()
	g.parse(ct.city_file)
	res1 = g.query("""
    PREFIX nit: <http://127.0.0.1:3333/>
    SELECT ?fname ?lname ?skill
    WHERE{
    	?x nit:hasFirstName ?fname.
    	?x nit:hasLastName ?lname.
    	?x nit:hasSkill ?skill
    }
    """)

	template = loader.get_template('worker/cityDetail.html')
	context = {
		'city_name' : city_name,
		'res1' : res1,
	}
	return HttpResponse(template.render(context,request))

worker/templates/worker/cityDetail.html
<h2>Details for city: {{ city_name }} </h2>

<table>
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Skill</th>
	</tr>
	{% for row in res1 %}
		<tr>
			<td>{{row.fname}}</td>
			<td>{{row.lname}}</td>
			<td>{{row.skill}}</td>
		</tr>
	{% endfor %}
</table>

worker/templates/worker/cityList.html
{% if all_cities %}
  <h3>Here are all the workers sorted by cities: </h3>
  <ul>
    {% for ct in all_cities %}
      <li><a href="{% url 'worker:cityDetail' ct.city_name%}">{{ ct.city_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <h3>You don't have any cities</h3>
{% endif %}

worker/templates/worker/index.html
{% if all_skills %}
  <h3>Here are all skills for workers You are searching for: </h3>
  <ul>
    {% for sk in all_skills %}
      <li><a href="{% url 'worker:skillDetail' sk.skill_name%}">{{ sk.skill_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <h3>You don't have any skills</h3>
{% endif %}





{% if all_cities %}
  <h3>Here are all cities we have data of: </h3>
  <ul>
    {% for ct in all_cities %}
      <li><a href="{% url 'worker:cityDetail' ct.city_name%}">{{ ct.city_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <h3>You don't have any cities</h3>
{% endif %}

worker/templates/worker/skillDetail.html
<h2>Details for skill: {{ skill_name }} </h2>

<table>
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Locality</th>
		<th>Sub-Skill</th>
	</tr>
	{% for row in res2 %}
		<tr>
			<td>{{row.fname}}</td>
			<td>{{row.lname}}</td>
			<td>{{row.local}}</td>
			<td>{{row.sub_skill}}</td>
		</tr>
	{% endfor %}
</table>

worker/templates/worker/skillList.html
{% if all_skills %}
  <h3>Here are all the workers sorted by skills: </h3>
  <ul>
    {% for sk in all_skills %}
      <li><a href="{% url 'worker:skillDetail' sk.skill_name %}">{{ sk.skill_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <h3>You don't have any workers</h3>
{% endif %}